### ISSUE TITLE
tabular data/ noisy instances/ new datasets

### ISSUE THREAD

**Issue by nazaretl** [gudovskiy/autodo#2]
Hi,
thanks for sharing your implementation. I have some questions about it:

1.	Does it also work on tabular data?
2.	Is the code tailored to the datasets used in the paper or can one apply it to any data?
3.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Thanks!

**Comment by gudovskiy** [comment]
Hi @nazaretl 
1. Not with the current data loaders
2. In general, it can be applied to any data, but not sure about augmentation model for e.g. tabular data
3. I didn't think about such application

**Comment by nazaretl** [comment]
thank you for the quick response!
